# Generated by Django 4.2.7 on 2024-06-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=60, null=True, unique=True, verbose_name='URL')),
                ('description', models.CharField(max_length=200, null=True, unique=True, verbose_name='Описание')),
                ('quantity', models.IntegerField(max_length=3, unique=True, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукт',
                'db_table': 'Products',
                'ordering': ('id',),
            },
        ),
    ]
