# Generated by Django 5.0.6 on 2024-06-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_products_img_products_price_alter_products_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, max_length=10, null=True, upload_to='users_orders', verbose_name='Изображения')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата Создания')),
                ('wish', models.TextField(blank=True, max_length=200, null=True, verbose_name='Пожелание')),
                ('username', models.TextField(max_length=40, verbose_name='Имя Пользователя')),
                ('first_name', models.TextField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('phone', models.TextField(max_length=18, verbose_name='Номер Телефона')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказ',
                'db_table': 'Orders',
                'ordering': ('-created_date',),
            },
        ),
    ]
